### ISSUE TITLE
unable to migrate to v.2 https://hexdocs.pm/nebulex/migrating-to-v2.html is broken

### ISSUE THREAD

**Issue by yatender-oktalk** [cabol/nebulex#102]
I was using nebulex v1.2.2 but with that version shards 0.6 was giving issue while compiling with OTP 23.
Then while upgrading shards was fine but decorator issue came up and there is a broken link for documentation.
Please guide me where I can check the link to upgrade to v2.

**Comment by cabol** [comment]
Yeah, that's because, for candidate releases like `2.0.0-rc.2`, hex doesn't update the root of the docs, until the release itself `2.0.0` is published, so it will be broken meanwhile. In the hex doc, on the top-left, you can select the version and set the `2.0.0-rc.2`, this is the link: https://hexdocs.pm/nebulex/2.0.0-rc.2/migrating-to-v2.html#content

**Comment by cabol** [comment]
Since Nebulex 2.0.0 was published, the link should be fixed already
