### ISSUE TITLE
TTL and EXPIRE functions?

### ISSUE THREAD

**Issue by cohawk** [cabol/nebulex#17]
Looking through the docs and codebase I do not see a way to return a key's current TTL - only set it.  Unless I am missing it somewhere? (https://redis.io/commands/ttl)

Also along those lines it would be nice to have a Redis like EXPIRE function (https://redis.io/commands/expire) to refresh a key's TTL (get and set) or return 0/false if the key does not exist (or already expired).

**Comment by cabol** [comment]
@cohawk I agree, it would be helpful to have these functions (especially the `ttl` to retrieve the remaining TTL for an specific key). But, I'm not sure to add them to the current cache interface.

1) For the TTL which is more related to the `Nebulex.Object` module, so I've added a function there in order to retrieve the remaining TTL. For Example:

```elixir
MyCache.set("foo", "bar", ttl: 10)
:timer.sleep(5000)

remaining_ttl =
  "foo"
  |> MyCache.get(return: :object)
  |> Nebulex.Object.ttl()
```

2) For the EXPIRE funtion, I think it is very easy to implement it using the current cache interface, for example:

```elixir
remaining_ttl =
  "foo"
  |> MyCache.update(nil, &(&1), ttl: 5, return: :object) # this acts as EXPIRE function
  |> Nebulex.Object.ttl()
```

Let me know your thoughts!

**Comment by cohawk** [comment]
@cabol, simple and beautiful.  Passing the &(&1) function is much better than the get_and_update method that I was looking into.

I think I would still create wrapper functions with documentation (at least in my code) using your above examples and explanations, since I could see myself looking back at the Expire code block and not remembering exactly what it was doing.

But either way both functions are now possible.  Thanks for your great work on the library!

**Comment by cabol** [comment]
@cohawk thanks :) !!
