### ISSUE TITLE
Feedback for NebulexLocalDistributedAdapter

### ISSUE THREAD

**Issue by martosaur** [cabol/nebulex#180]
Hi @cabol 👋 

We at Slab have been working on [NebulexLocalDistributedAdapter](https://github.com/slab/nebulex_local_distributed_adapter) for some time and we'd love to know your opinion before we publish it to Hex. We've noticed that our adapter is similar to the Near Cache mentioned in https://github.com/cabol/nebulex/issues/50, but it also quite different in invalidation strategies. There is a brief description of how LocalDistributed adapter works in [readme](https://github.com/slab/nebulex_local_distributed_adapter#how-it-works).

Our question is, do you think we should rename our adapter to NebulexNearCacheAdapter? If you'd like to peak at the code, it's all in a single PR at https://github.com/slab/nebulex_local_distributed_adapter/pull/1. Any feedback is greatly appreciated!

**Comment by cabol** [comment]
Hey @martosaur 👋 !! That's awesome, there more alternatives for adapters the better!!

Regarding the name, well, that's tough, let me give my thoughts. IMHO, the name `NebulexNearCacheAdapter` sounds a bit better to me than `NebulexLocalDistributedAdapter`, it is more specific. But, since this is a variation of the multi-level adapter, perhaps you can also think of a name like `NebulexSlabMultilevelAdapter` maybe? Overall, the adapter looks 👌, nice work, looking forward to the release in Hex. Then, you can open a PR to Nebulex adding it to the adapters list (looking forward to it too).

**Comment by martosaur** [comment]
@cabol Thank you! After another round of discussion we went with `LocalMultilevelAdapter`. The adapter is now published on Hex and I created a PR to mention it in readme https://github.com/cabol/nebulex/pull/185
