### ISSUE TITLE
Unable to use module attributes when specifying a MFA cache within the decorator

### ISSUE THREAD

**Issue by suzdalnitski** [cabol/nebulex#191]
Hi,

The following works:

```elixir
@decorate cacheable(
            cache: {MyApp.Cache, :get_cache, []},
            key: @some_key,
            opts: [ttl: @cache_ttl]
          )
def some_func do
```

While the following fails:

```elixir
@my_cache {MyApp.Cache, :get_cache, []}

@decorate cacheable(
            cache: @my_cache,
            key: @some_key,
            opts: [ttl: @cache_ttl]
          )
def some_func do
```

The error I'm getting is:

```
** (ArgumentError) you attempted to apply a function on {MyApp.Cache, :get_cache, []}. Modules (the first argument of apply) must always be an atom
(nebulex 2.4.2) lib/nebulex/caching.ex:827: Nebulex.Caching.run_cmd/5
```

Is this expected behaviour?

Thanks!

**Comment by cabol** [comment]
Hey 👋 !! Yeah, that is expected because the `:cache` option is resolved in compilation time, so when you do something like `cache: @my_cache` in the decorator, since it is a constant, what is received in the decorator is the constant itself, means the cache will be that constant, not expanded value. However, this is something we can handle maybe in runtime, making this possible, I will think about that option (handling the `:cache` option in tuntime) and maybe create a separate ticket. In the mean`tine, yeah, it is an expected behavior.

**Comment by suzdalnitski** [comment]
That makes sense, thank you!
