### ISSUE TITLE
Unregistering cache in registry happens after cache shuts down

### ISSUE THREAD

**Issue by martosaur** [cabol/nebulex#194]
Hi @cabol 👋 

I was debugging `1st argument: the table identifier does not refer to an existing ETS table` error we sometimes see in our production logs and I traced it back to [this place](https://github.com/cabol/nebulex/blob/6da0b5407749b0edb0d500fd0c41423e6c2844ef/lib/nebulex/cache/registry.ex#L46-L50) in `Nebulex.Cache.Registry`. Basically, we deregister cache in Registry _after_ supervisor shut down, which leaves a tiny window of time during which client can successfully lookup cache process, but cache itself is being shut down.

It looks to me that it will make sense to unregister cache before we actually begin to shutdown supervisor process and its workers. This won't eliminate the race condition entirely, but I feel like it will make for a nicer shutdown and translate a whole family of obscure errors to a simple `Nebulex.RegistryLookupError`

I didn't come up with an obvious way to implement this, so decided to create an issue first to get some feedback. But I wrote a [failing test](https://github.com/cabol/nebulex/commit/aac720e7a8c81d7c3020709cfd8e3033c64b65dd) that should help in the future!

**Comment by cabol** [comment]
Hey 👋 !! Yeah, like you said, there is no obvious way to address this. I agree a different exception like `Nebulex.RegistryLookupError` may look a bit better, but the problem is still there. Unregister before to shutdown I don't think is a right solution because, first of all, the cache supervisor is can be explicitly stopped or it can just crash, and in that case, where are we ging to unregister? Second of all, unregister means delete the context from the Registry which uses the `:persistent_term`, and that could be expensive, that's why it is handled by the registry itself monitoring the cache supervisor process, and when it dies, it it unregistred (similar to Ecto for example). I will think about it, see if there is something we can do about it, but I think it is important to understand your use case also, maybe I can help you more. For example, why the cache is crashing or why you are stopping it? How your main supervision tree is configured, because, if you have other processes depending on the cache, perhaps you can use another strategy like `:rest_for_one` ensuring when the cache supervisor is restarted, their dependants are restarted too. anyway, it is just to throw some ideas, let me know your thoughts. Thanks!

**Comment by martosaur** [comment]
Registry can still listen to supervisor exit messages and unregister in case supervisor didn't do this!

> I will think about it, see if there is something we can do about it, but I think it is important to understand your use case also, maybe I can help you more. For example, why the cache is crashing or why you are stopping it? How your main supervision tree is configured, because, if you have other processes depending on the cache, perhaps you can use another strategy like :rest_for_one ensuring when the cache supervisor is restarted, their dependants are restarted too. anyway, it is just to throw some ideas, let me know your thoughts

Our use case is nothing special: we have Cache process in our main Application supervisor tree and we see errors on the app shutdown, since there's still some residual traffic from client processes on other nodes (we use [this adapter](https://github.com/slab/nebulex_local_multilevel_adapter) which broadcasts events to other nodes).

One possible way to go about this is to have special worker process among supervisor children which will unregister on exit. The same way `Bootstrap` process is used to leave cluster in Partitioned and Replicated adapters
