### ISSUE TITLE
random :erpc, :timeout with partitioned get

### ISSUE THREAD

**Issue by benonymus** [cabol/nebulex#202]
Hey,

I have the following cache:
```
  use Nebulex.Cache,
    otp_app: :app,
    adapter: Nebulex.Adapters.Partitioned
```
I randomly saw this error:  
```
Nebulex.RPCError The RPC operation failed on node :"app@fdaa:0:0000:a9b:80:fdac:28d3:2" with reason:

{:erpc, :timeout}

See :erpc.call/5 for more information about the error reasons.
```
from here (lib/nebulex/rpc.ex in Nebulex.RPC.rpc_call/6 at line 138): https://github.com/cabol/nebulex/blob/b12bd5a3e3430184726508073dc5c243624e1a71/lib/nebulex/rpc.ex#L138 

Does this mean I should raise the timeout? https://hexdocs.pm/nebulex/getting-started.html#timeout-option

I also saw one of these: 
```
Uncaught exit - {:timeout, {Task.Supervised, :stream, [5000]}}
``` 
the same time from another function that uses get from nebulex.

It was a one off not around deployment or any scaling.

**Comment by cabol** [comment]
Hey!

> Does this mean I should raise the timeout? https://hexdocs.pm/nebulex/getting-started.html#timeout-option

By default the timeout is `5000` (5 sec), so maybe you should use the `:timeout` option, but the error may happen anyway because the cache is trying to reach a node to perform the operation and timed out, that may still happen. So I think if this is something you see from time to time, better off handling/rescuing the exception, then, if the reason is `{:erpc, :timeout}` perhaps you may want to retry, or just ignore it.

> I also saw one of these:
> `Uncaught exit - {:timeout, {Task.Supervised, :stream, [5000]}}`

This one looks a bit weird, because `:erpc` is used for OTP >= 23, otherwise, it uses supervised tasks. May you add the whole stacktrace please?

**Comment by benonymus** [comment]
Have not seen this since, so closing it.
