### ISSUE TITLE
Having a cache per user ID...

### ISSUE THREAD

**Issue by hickscorp** [cabol/nebulex#224]
Very likelly a question more than a feature request.

We're trying to understand if Nebulex would support having cache processes spun-up dynamically at runtime based on an argument (Eg an ID).
The goal is to have as many caches as users - for  example - so waiting operations aren't shared between users.

Typically, we would have something like this in our `application.ex`:

```elixir
[..., {DynamicSupervisor, name: MyApp.UserTeamsCache.supervisor_name()}]
|> Supervisor.start_link(strategy: :one_for_one, name: MyApp.Supervisor)
```

Then `UserTeamsCache` would look like:

```elixir
defmodule MyApp.UserTeamsCache do
  @moduledoc false
  use Nebulex.Cache, otp_app: :my_app, adapter: Nebulex.Adapters.Local
  use Nebulex.Caching.Decorators

  @me __MODULE__

  def supervisor_name(),
    do: @me.Supervisor

  @decorate cacheable(cache: {__MODULE__, :which_cache, []}, key: id)
  defp something(id) do
    ... # Thing that needs to be cached in a separate PID per ID...
  end

  def which_cache(mod, fun, [id] = args) do
    # What should this function return? Should it spin up the cache itself, based on the ID?
    ...
  end
end
```

We played around with `with_dynamic_cache` and others, but no cigar so far.

Thank you!

**Comment by hickscorp** [comment]
Good afternoon @cabol and thanks for taking the time.

I understand that we might have to wait for v3 release to use dynamic (runtime) spun-up caches.

> What are the waiting operations you mention? I'm asking because I've had a similar scenario with a lot of users and a high workload, using one cache, and never had an issue, so, maybe I can help?
It might be very much my misunderstanding of how Nebulex works under the hood. Let me run a scenario for you to tell me if I'm wrong.

- Imagine a function that takes a user ID. This function is computationaly intensive. It takes a long time to complete.
- We annotate this function with a decorator making it `cacheable(CacheModule, key: user_id)`.

So far so good.

Now I'm assuming that the function runs inside the cache process - so when the cache is being primed, it's mailbox is waiting.
So if you have two different requests, from two different users, I'm assuming that the 2nd user is awaiting the end of the cache being primed for the 1st user to be able to continue?
Or is Nebulex spining up one GenServer under the hood per cache key?...

That's it :) Hopefully you understand better what I meant and maybe you can immediatelly spot the flaw in my reasoning?

**Comment by cabol** [comment]
Hi @hickscorp!

> Now I'm assuming that the function runs inside the cache process - so when the cache is being primed, it's mailbox is waiting.
> So if you have two different requests, from two different users, I'm assuming that the 2nd user is awaiting the end of the cache being primed for the 1st user to be able to continue?
> Or is Nebulex spining up one GenServer under the hood per cache key?...

Right. Let me try to explain. This depends 100% on the cache adapter (and the cache implementation underneath). But none of the Nebulex adapters behave that way. For example, the local adapter (same as the Cachex adapter) uses ETS tables underneath, so when you hit the cache it goes directly to the table (backend), there is no single process channeling the cache commands, it hits the backend directly leveraging the concurrency capabilities of the ETS tables. The adapters were designed to avoid a single process bottleneck. But again, this depends entirely on the adapter. You can build an adapter for another cache that implements a single process strategy, and in that case, it may be a problem as you mentioned. So, you don't need to worry about that because that is not going to happen, it is not how Nebulex and its adapters work.

Please let me know if it makes sense, I know it may be confusing 😅 . I stay tuned!

**Comment by hickscorp** [comment]
@cabol this is such an extensive answer, thanks a lot for taking the time.
We can close the issue!
