### ISSUE TITLE
Update Getting Started guide

### ISSUE THREAD

**Issue by ferigis** [cabol/nebulex#4]
In "Fetching all entries" section we are using `Blog.Cache.all/0,1` which it doesn't exist anymore.
Replace it by `to_map` function

**Comment by loongmxbt** [comment]
May I ask why replace all() to to_map()?

**Comment by cabol** [comment]
@loongmxbt the reason is `all` function doesn't exists any more, instead the `to_map` function was created to retrieve all cached entries, because sometimes you might want not only the values but also the keys, and I though the best way to return the cached entries was using a map, you have both, keys and values, and is you want the `Nebulex.Object` as value, you can pass the option `return: :object`.

However, if you have any suggestion, possible enhancement, please let us know :)

Stay tuned!
