### ISSUE TITLE
Replicated hash_slots for partitioned adapter.

### ISSUE THREAD

**Issue by seivan** [cabol/nebulex#65]
I know it's a bit of a stretch since you're kinda supposed to have a record store to fill from with a cache miss, but I do wonder if it could technically make sense to cache the slot with a replication? 

It might be dumb and silly, but just a thought here: 
One of the reasons one might want sharding instead of replication is because it might be too much data to replicate across all nodes and hold in memory. 
But what if the dataset itself is small enough so it's not an issue replicating **where** the data is stored. 

For instance, maybe I've misunderstood how the partition adapter works, but 
But going from 3 nodes to 4 nodes there might be a potential leak? 
```elixir
#Three nodes 
iex[node0]> "hello" |> :erlang.phash2 |> :jchash.compute(3) 
0
#Four nodes 
iex[node3]> "hello" |> :erlang.phash2 |> :jchash.compute(4)
3
#Nine nodes 
iex[node8])> "hello" |> :erlang.phash2 |> :jchash.compute(9)
8
```

The key stored in `node0` is no longer accessible so every cache hit will be a miss. 
However `node0` still stores the key while any current `get/set` will hit `node3` with four nodes, and `node8` at nine nodes. 

Not a biggie as nodes will go up and down, as you keep adding nodes a lot of keys will be invalidated. A potential solution is migrating keys over as new nodes are added and deleted, another potential solution (that only tackles adding) would be to replicate which node holds what key. 

For `get`
Would it make sense to replicate `"hello" -> node0` association across nodes for a lookup before calculating the hash slot? 

For `set` it would update the hash slot across the replicas **if** it has changed, otherwise the association remains. 

Could just dog food the replication adapter internally and use it for storing the look ups. 
A positive side effect would be that it's easier to tell local stored keys and avoid the RPC calls all together. 
Meaning a `get()` would know if the key is part of the local cache and could fetch it directly from there. 

Again this might be dumb or an already solved issue.

**Comment by cabol** [comment]
First of all, thanks for your thoughts on this 👍, they make a lot of sense and actually they open the door for other ideas as well.

The partitioned adapter implements sharding as a distribution model, which brings with pros and cons, let's talk about the cons:

- If one of the nodes of the cluster goes down, part of the data becomes unavailable. In terms of losing data, this shouldn't be a big issue, since you should have an SoR so the data can be retrieved from there and cached again (check [Cache Usage Patterns via Nebulex.Caching DSL](https://hexdocs.pm/nebulex/caching-dsl.html)).

- Adding and/or removing nodes causes the keys to having to be re-hashed. This is what the consistent-hashing aims to mitigate (mitigate, not to solve the problem completely), but it happens anyways causing cache misses for a period of time (until the keys are re-hashed on-demand and the cache gets stabilized again). Now, it is true that there will be nodes storing data that won't be fetched never again, but eventually, that data should be expired and that space claimed back again (avoiding a potential memory leak).

On the other hand, if we can decrease cache misses somehow that would be great, but I'm not sure if replicate the hash-slot makes sense since we would end up replicating the keys across all nodes, in that case, why not just replicate the data, maybe because memory space since the value may require more than just the node, right? But overall, that looks more like the replicated topology, and in that case, maybe it could be better to use the replicated adapter  `Nebulex.Adapter.Replicated`.

One of the ideas I've considered to this is to create another adapter, with a different distribution model: "Sharding + Peer-To-Peer Replication", splitting the data across the cluster uniformly plus a replication factor, but it is not trivial implementation (maybe we can create a separate repo for this new adapter and use Riak Core or something similar t make things easier), and I'd like to be sure it's really worth it.

Thanks again and I stay tuned for your comments!

**Comment by seivan** [comment]
> If one of the nodes of the cluster goes down, part of the data becomes unavailable. In terms of losing data, this shouldn't be a big issue, since you should have an SoR so the data can be retrieved from there and cached again (check Cache Usage Patterns via Nebulex.Caching DSL).

Yep, I mentioned that with `you're kinda supposed to have a record store to fill from with a cache miss,` but I think there's a gray area here and I'll get to that later. 

> Adding and/or removing nodes causes the keys to having to be re-hashed. This is what the consistent-hashing aims to mitigate (mitigate, not to solve the problem completely), but it happens anyways causing cache misses for a period of time (until the keys are re-hashed on-demand and the cache gets stabilized again)

The consistent hashing example I posted above will be pretty unstable until 10 nodes, in which case it starts becoming stable. But if you're in an auto scaling environment you might just keep toggling between and that will cause issues.
Granted  owever on larger nodes it's a moot problem. 

It's an unnecessary problem to be honest since there's already code for Replication to solve it. 

> Now, it is true that there will be nodes storing data that won't be fetched never again, but eventually, that data should be expired and that space claimed back again (avoiding a potential memory leak).

Regarding the "leak",  what I suggested would make take care of that as a side effect - one smaller "issue" dealt with.  However keep in mind if anyone deploys long living services with auto scaling below 10 nodes and don't use TTL they will essentially leak. 


> in that case, why not just replicate the data, maybe because memory space since the value may require more than just the node, right? But overall, that looks more like the replicated topology, and in that case, maybe it could be better to use the replicated adapter Nebulex.Adapter.Replicated.

It looks like Replication because it is -  just for the keys with the actual values being partitioned. 
I am saying use the Replicated adapter internally for the partitioned.ex adapter for managing the `hash_slots` and **only** that. 

Replicating the `hash_slots` is going significantly more lightweight both memory wise and bandwidth than entire caches no matter how you cut it. 
There are scenarios where Replication for actual cache is unusable. 

Which brings me to what I mentioned earlier regarding the gray area for certain types of data. 

There is certain data that sorta fits in between persistent and ephemeral, for instance something like `Auth/Sessions`. 

Now we could store our Session in the db and when a cache miss happens, just rehydrate the cache from the db.
However, what if you don't want to store Sessions in the db? They're not long lived, they will not be used for anything else and it's just annoying to have a persistent row for something that's somewhat ephemeral. 
We still want something to look up against, because maybe we want the ability to revoke a session, that would be deleting it from cache. 

If one were to use the database for the Session, with a revoke you would have to delete from the cache **and** the db. 

Nebulex with partitioning is a *perfect* fit, except that I think it's unreasonable to miss the cache when you scale from 3 nodes to 4 nodes potentially logging out all users. 

I am ok with making a PR using replication for `hash_slots` inside the Sharded adapter as opt in if you're comfortable with the idea.

**Comment by cabol** [comment]
I mean, that makes a lot of sense, and if we can do something to improve the current partitioned adapter that would be great. So, if you can contribute with this, either as something optional for the partitioned adapter or even as another or separate adapter (using the partitioned and/or replicated under-the-hood), it would be awesome! Looking forward to it 😀 !

**Comment by seivan** [comment]
Hey, sorry for the massive delay.

First off, nice work adding the decorators! I actually think it solves some of the issues (with some tweaks) I was bringing up earlier depending on how Nebulex behaves when the hashing fails because new nodes added or removed. 

So let me explain my trail of thoughts and correct me if I am wrong: 

1
When a node is added, which causes a key lookup to fail because the hash became different, it will be considered a "miss", correct?
\
\
  2 
Since we didn't give it a `TTL` it is now considered a leak, somewhere some node is storing the cached value, but no other node will hit that particular node, because the hashing algorithm returns a different value. 

Is this leak handled in anyway or removed? 
\
\
3
Which  means when using decorators such as 
```elixir
  @decorate cache(cache: Cache, key: {User, id})
  def get_user!(id) do
    Repo.get!(User, id)
  end
```
It will miss, causing the function to execute and store the new value to the *new* node that the algorithm says it should store with? 
\
\
4
So the only issue is the "leak" stored value in one of the nodes that will never be accessed, correct?

**Comment by cabol** [comment]
NP at all!

> When a node (Node4) is added, which causes a key lookup on a value stored on Node0 to fail because the hash became different, it will be considered a "miss", correct?

Correct, it will be considered a "miss".

> Since we didn't give it a TTL it is now considered a leak, somewhere Node0 is storing the cached value, but no other node will hit that particular node, because the hashing algorithm says to look at Node4. Is this leak handled in anyway or removed?

Yes, in the case of the local adapter, at some point the GC will run pushing a new generation and that "unused" entry will be evicted. Normally, this is a job performed by the eviction policy implemented by the cache, in the local adapter, which is a generation cache, the eviction is cased by pushing new generations. So again, if you are using the local adapter and you have set the `gc_interval` option, the entry that considered a "leak" will be evicted by the GC when the oldest generation is removed; since that entry won't be hit anymore, it will be pushed the oldest generation at some point.

> The only issue is the "leak" stored value in Node0 that will never be accessed, correct?

I think the previous answer address this one, right? If it doesn't let me know.

If the `gc_interval` has been set properly, it doesn't matter if you don't set a TTL, the GC will run and at some point, the unused keys will be evicted.

Let me know if this answers your questions and concerns, stay tuned!

Thanks.

**Comment by cabol** [comment]
I'm closing this issue. Feel free to re-open it if you come up with more insights or doubts about it.
